apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJob3N0Lm1pbmlrdWJlLmludGVybmFsOjUxMDAiOnsidXNlcm5hbWUiOiJBV1MiLCJwYXNzd29yZCI6InRlc3QiLCJhdXRoIjoiUVZkVE9uUmxjM1E9In19fQ==
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: targeting-service
type: kubernetes.io/dockerconfigjson
