apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: targeting-service
type: Opaque
data:
  # echo -n "postgresql://postgres:postgres@host.minikube.internal:7003/postgres" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGhvc3QubWluaWt1YmUuaW50ZXJuYWw6NzAwMy9wb3N0Z3Jlcw==
