apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: flag-service
type: Opaque
data:
  # echo -n "postgresql://postgres:<SENHA>@<RDS-FLAG-ENDPOINT>:5432/postgres" | base64
  DATABASE_URL: PREENCHER_APOS_CRIAR_RDS
