apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
data:
  # echo -n "postgresql://postgres:postgres@host.minikube.internal:7001/postgres" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGhvc3QubWluaWt1YmUuaW50ZXJuYWw6NzAwMS9wb3N0Z3Jlcw==
  # echo -n "local-dev-master-key" | base64
  MASTER_KEY: bG9jYWwtZGV2LW1hc3Rlci1rZXk=
