apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: evaluation-service
data:
  PORT: "8004"
  REDIS_URL: "redis://host.minikube.internal:6379"
  FLAG_SERVICE_URL: "http://flag-service.flag-service.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting-service.svc.cluster.local:8003"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://host.minikube.internal:4566"
  AWS_SQS_URL: "http://host.minikube.internal:4566/000000000000/togglemaster-queue"
