apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: evaluation-service
          image: host.minikube.internal:5100/000000000000/togglemaster/evaluation-service:latest
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: evaluation-service-secret
            - configMapRef:
                name: evaluation-service-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
