apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
type: Opaque
data:
  # echo -n "test" | base64
  AWS_ACCESS_KEY_ID: dGVzdA==
  # echo -n "test" | base64
  AWS_SECRET_ACCESS_KEY: dGVzdA==
stringData:
  # Preencher após ETAPA 3 bootstrap: echo -n "<api-key-gerada>" | base64 
  #"PREENCHER_APOS_BOOTSTRAP"
  SERVICE_API_KEY: dG1fa2V5XzUyMzBjNTM2MzMwN2MxNjFiNGNkNTZiZjE2ZTMwMTRmMDE1ZWIxMzUxYjVjOTYzMmYwNzY2NmM0OWRiM2I2Njg==
