apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-service
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  # SUBSTITUIR: troque <ACCOUNT_ID> pelo seu AWS Account ID (12 dígitos)
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/togglemaster-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
