apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-scaler
  namespace: analytics-service
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: http://host.minikube.internal:4566/000000000000/togglemaster-queue
        queueLength: "5"
        awsRegion: us-east-1
        awsEndpoint: http://host.minikube.internal:4566
      authenticationRef:
        name: keda-sqs-trigger-auth
