apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics-service
type: Opaque
data:
  # echo -n "test" | base64
  AWS_ACCESS_KEY_ID: dGVzdA==
  # echo -n "test" | base64
  AWS_SECRET_ACCESS_KEY: dGVzdA==
