apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics-service
type: Opaque
data: {}
# Sem credenciais AWS — pod usa IRSA via serviceaccount analytics-service-sa
