apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: analytics-service
  annotations:
    # SUBSTITUIR: troque <ACCOUNT_ID> pelo seu AWS Account ID (12 dígitos)
    # ATENÇÃO: este arquivo é referência — NÃO aplicar via kubectl
    # O eksctl create iamserviceaccount (ETAPA 5) cria este ServiceAccount automaticamente
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/togglemaster-analytics-role
