apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: flag-service
type: Opaque
data:
  # echo -n "postgresql://postgres:postgres@host.minikube.internal:7002/postgres" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGhvc3QubWluaWt1YmUuaW50ZXJuYWw6NzAwMi9wb3N0Z3Jlcw==
