apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
data:
  # echo -n "postgresql://postgres:<SENHA>@<RDS-AUTH-ENDPOINT>:5432/postgres" | base64
  DATABASE_URL: PREENCHER_APOS_CRIAR_RDS
  # echo -n "<master-key-segura>" | base64
  MASTER_KEY: PREENCHER
